on:
  issues:
    types: [labeled]

jobs:
  automate_invite:
    runs-on: ubuntu-latest
    steps:
      - name: Invite on label
        uses: vj-abigo/invite-on-label@v1.4
        with:
          organization: GDSC-RVTTI
          label: Invitation to the community 
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          comment: 'Welcome to the Org.'
        env:
          INVITE_TOKEN: ${{ secrets.GDSC_INVITE }}
